/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import { Suspense, lazy } from "react";
import MainLayout from "@/layout/MainLayout";
import Head from "next/head";
import Preloader from "@/components/Loader";
import Services from "@/components/Services";
import Aboutus from "@/components/Aboutus";
import Contactus from "@/components/Contactus";

// Importa los componentes de forma diferida (lazy)
const Banner = lazy(() => import("@/components/Banner"));
const Courses = lazy(() => import("@/components/Courses"));
// Añade más importaciones diferidas según sea necesario para otros componentes

export default function Home() {
  return (
    <>
      <Head>
        <title>soslogic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.ico" />
      </Head>

      <MainLayout>

        <img className="fadeIn shape-banner d-none d-md-block" src="/banner/hero-shape.png" loading="lazy" />
        <img className="fadeIn shape-banner-left" src="/banner/blur-layer.png" loading="lazy" />
        <img className="fadeIn shape-banner-bottom" src="/banner/half-circle.png" loading="lazy" />
        <img className="fadeIn banner-people_team" src="/banner/people_team.png" loading="lazy" />
        <Banner />

        <Courses />

        {/* Renderiza más componentes diferidos aquí según sea necesario */}
        <Services />
        {/* <Aboutus /> */}
        {/* <Team /> */}
        {/* <Testimonials /> */}
        <Contactus />
      </MainLayout>
    </>
  );
}
