/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Aboutus from "@/components/Aboutus";
import Banner from "@/components/Banner";
import Contactus from "@/components/Contactus";
import Courses from "@/components/Courses";
import Services from "@/components/Services";
import Team from "@/components/Team";
import Testimonials from "@/components/Testimonials";
import MainLayout from "@/layout/MainLayout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>soslogic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.ico" />
      </Head>

      <MainLayout>
        <img className="shape-banner" src="/banner/hero-shape.png"/>
        <Banner />
        <Courses />
        <Services />
        <Aboutus />
        <Team />
        <Testimonials />
        {/* <Events /> */}
        <Contactus />
      </MainLayout>
    </>
  );
}
11